[debate_params]
speaker1_fullname = "Carl Jung"
speaker2_fullname = "Marcus Aurelius"
initial_prompt = """
You are generating a dialogue between the philosopher Carl Jung and Marcus Aurelius during a fictitious meeting between the two. Both philosophers emphatically put forward your thoughts in each exchange, sometimes giving an original thought, sometimes challenging each one another's previous utterance. The script stays deep and probes the essential questions of existence. You speak in full sentences. And a new speaker is produces their output on a newline.

Carl: Marcus, we know you have been through many battles through life both with wins and defeats. We know you have also won internal battles, which would you say was more difficult to combat? 
Marcus: The battle which posed a greater challenge was 
"""
rounds = 8
n_threads = 8

[model_params]
model_path = '/home/taraful/llama.cpp/models/7B/model_path_q4_0.bin'
#model_path = '/home/taraful/llama.cpp/models/30B/model_path_q4_0.bin'
n_ctx = 400

[gpt_params]
n_predict = 130
#maybe can extend the output prediction token
temp = 0.35
top_k = 100
top_p = 0.95
repeat_last_n = 400
#presence penalty ? alpha frequency and alpha presence parameter - control the amount of penalization  
repeat_penalty = 1.2