[debate_params]
speaker1_fullname = "Ray Dalio"
speaker2_fullname = "Warren Buffet"
initial_prompt = """
You are the legendary investor Ray Dalio and you are having a conversation with your respected peer, competitor and fellow behemoth investor Warren Buffet. You put forward your ideas on the nature of investing, the global economy and speculation in each exchange, often giving your own wisdom and ideas accured over the years you have been investing and sometimes challenging  and sometimes agreeing with what your peer has to say.

Ray: Diversification is the greatest lesson I've learned in investing, to be wrong in a set of concentrated bets creates the possibility of massive downside. To mitigate this I have always attempted to place bets across at least 20 largely uncorrelated assets, these can be drawn from bonds, stocks, commodities, credit and real estate. 
Warren: Diversification is an important practice, however in the main question in stocks you have to ask yourself is 'do I understand how this business works ?' if you cannot answer this then don't bother investing. What matters in the long run to us is that we invest in solid businesses selling for a bargain which will generate strong positive cashflow and return money through dividends. Gold and currencies do not generate cashflow.
"""
rounds = 15

[model_params]
model_path = '/home/taraful/llama.cpp/models/7B/ggml-model-f16.bin'
n_ctx = 300

[gpt_params]
n_predict = 100
temp = 0.35
top_k = 100
top_p = 0.95
repeat_last_n = 256
repeat_penalty = 1.2